name: Continuous Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@latest

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@latest
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache dependencies
              uses: actions/cache@latest
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Install dependencies
              run: pnpm install

            - name: Run the lints
              run: pnpm run lint

            - name: Run Prettier
              run: pnpm run prettier:ci

            - name: Run the tests
              run: pnpm run test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@latest

            - name: Build
              run: pnpm run micro:build

            - name: Archive production
              uses: actions/upload-artifact@latest
              with:
                  name: build
                  path: |
                      build
                      !build/**/*.md
